### ISSUE TITLE
Evaluation 2

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/jqfundamentals#14]
On clicking + img in "ToDos sec" against each employee, add a todo input area with a save & cancel image links next to it. 

On saving, replace it with text in a div with edit & remove image links against it. 

-You can use an in-place edit plugin or can hand code it. 
- As ToDos start growing and gets more than 3 for one user, show a vertical scroll instead of occupying more vertical space(can do it through css also) 
- Try using visual effects to play it nicely. 

Clicking remove link against the todo should delete that todo. 
If all Todos for a user are removed bring back the text "Add todos of user" 

Expand all/Collapse all buttons on top of "ToDos section" as shown in the image and should expand/collapse all the Role headers with respective employee's data under them. 

There should be a Search field on the top of the page where user can put number of Todos and it should collapse all Role headers but the ones that have employees under it meeting the search criteria and flashing the employee names for few seconds(just the name on the left not todos) 

Obviously the other employees under the expanded Role header will be shown too but flashing will be done only on the ones that meet the search criteria. 

During search, lets assume that none of the todos are in edit state or new todo state. 

Note: don't keep a count of Todos stored anywhere, structure the html properly so can count todo containers under each employee. 
Negative numbers, alphabets can't be entered. 

On hovering an employee under "Employees section" a delete image link will be show on right side, clicking which a confirmation will be shown followed by removing that employee instances from all places on the page. Note: use the existing code thats already written for removing employee from "Roles sec"

https://github.com/wilsonokibe/jqfundamentals/tree/master/JQUERY_EXERCISES/evaluation2

**Comment by wilsonokibe** [comment]
updated

**Comment by wilsonokibe** [comment]
Updated and complete
https://github.com/wilsonokibe/jqfundamentals/tree/master/JQUERY_EXERCISES/EVALUATION

**Comment by segunadeleye** [comment]
Much more improved code structure.

## assignment.js

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/assignment.js#L29; This can be done without using a loop. You should be able to select the actual element.

## employee.js

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/employee.js#L19; This can be reduced to a chain.

## main.js

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L52; how about calling this.addRole() and then do your validation within it. It's in the process of adding the role that validation takes place. Moreover, input should not get hidden if validation fails
Also, improper method name; this is not returning true or false.

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L62; how about calling this.addEmployee() and then do your validation within it. It's in the process of adding that validation takes place. Moreover, input should not get hidden if validation fails

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L67; Will Will `let selectedRoleElement`; not work?

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L75; do we need to still pass `dataId` as an argument?

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L185 and https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L210; `showRoleInputField()` and `showEmployeeInputField()` can be a method

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L234; Do this without using a loop.

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L265 and https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L270; How about making `hideEmployeeInputField()` and `hideRoleInputField()` a method

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L301 ...can become

`createSaveImageButton(containerId) {`
   `return $('<img />', {`
      `'id': 'save-button-' + containerId,` 
     `'class': 'save-button-image',`
      `'src': 'images/OK.png',`
     `'data-id': containerId`
   `});`
`}`
Do this for similar methods.

## search.js

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/search.js#L32; Try using while-loop to do this.

**Comment by wilsonokibe** [comment]
Updated

**Comment by segunadeleye** [comment]
https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L234; Is there a need for this?

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L225; Use proper naming convention

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L248 and https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L253; which of the two methods are you using?

https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L229; we can do away with this `if` and its `else` (https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/main.js#L238) ...keeping just the inner if-statement

same as https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/assignment.js#L31 and https://github.com/wilsonokibe/jqfundamentals/blob/master/JQUERY_EXERCISES/EVALUATION/js/assignment.js#L38

**Comment by segunadeleye** [comment]
All good now :+1:
