### ISSUE TITLE
Exercise 3.2 Traversing

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/jqfundamentals#7]
3.2 Traversing

Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:

Select all of the image elements on the page; log each image’s alt attribute.

Select the search input text box, then traverse up to the form and add a class to the form.

Select the list item inside #myList that has a class of “current” and remove that class from it; add a class of “current” to the next list item.

Select the select element inside #specials; traverse your way to the submit button.

Select the first list item in the #slideshow element; add the class “current” to it, and then add a class of “disabled” to its sibling elements.

https://github.com/wilsonokibe/jqfundamentals/tree/master/JQUERY_EXERCISES/Exercise3/Exercise3.2

**Comment by segunadeleye** [comment]
Please fix based on feedback in Issue 3.3

**Comment by wilsonokibe** [comment]
fixed
